Improve firmware diversions

diff --git a/debian/raspberrypi-re4son-firmware.postrm b/debian/raspberrypi-re4son-firmware.postrm
--- a/debian/raspberrypi-re4son-firmware.postrm
+++ b/debian/raspberrypi-re4son-firmware.postrm
@@ -1,17 +1,48 @@
 #!/bin/sh
-if dpkg-divert --list | grep -F "/lib/firmware/brcm/brcmfmac43430-sdio.bin"; then
-    dpkg-divert --package raspberrypi-re4son-firmware --remove --divert /lib/firmware/brcm/brcmfmac43430-sdio.bin.original --rename /lib/firmware/brcm/brcmfmac43430-sdio.bin
-fi
-if dpkg-divert --list | grep -F "/lib/firmware/brcm/brcmfmac43430-sdio.txt"; then
-    dpkg-divert --package raspberrypi-re4son-firmware --remove --divert /lib/firmware/brcm/brcmfmac43430-sdio.txt.original --rename /lib/firmware/brcm/brcmfmac43430-sdio.txt
-fi
-if dpkg-divert --list | grep -F "/lib/firmware/brcm/brcmfmac43455-sdio.bin"; then
-    dpkg-divert --package raspberrypi-re4son-firmware --remove --divert /lib/firmware/brcm/brcmfmac43455-sdio.bin.original --rename /lib/firmware/brcm/brcmfmac43455-sdio.bin
-fi
-if dpkg-divert --list | grep -F "/lib/firmware/brcm/brcmfmac43455-sdio.clm_blob"; then
-    dpkg-divert --package raspberrypi-re4son-firmware --remove --divert /lib/firmware/brcm/brcmfmac43455-sdio.clm_blob.original --rename /lib/firmware/brcm/brcmfmac43455-sdio.clm_blob
-fi
-if dpkg-divert --list | grep -F "/lib/firmware/brcm/brcmfmac43455-sdio.txt"; then
-    dpkg-divert --package raspberrypi-re4son-firmware --remove --divert /lib/firmware/brcm/brcmfmac43455-sdio.txt.original --rename /lib/firmware/brcm/brcmfmac43455-sdio.txt
-fi
+#!/bin/sh
+# postrm script for raspberrypi-re4son-firmware
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+	    remove)
+	        for files in /lib/firmware/brcm/brcmfmac43430-sdio.bin \
+		             /lib/firmware/brcm/brcmfmac43430-sdio.txt \
+		             /lib/firmware/brcm/brcmfmac43455-sdio.bin \
+		             /lib/firmware/brcm/brcmfmac43455-sdio.clm_blob \
+		             /lib/firmware/brcm/brcmfmac43455-sdio.txt; do
+                    rm -f $file		
+                    if dpkg-divert --list | grep -F "${file}"; then
+                        dpkg-divert --package raspberrypi-re4son-firmware --remove --divert $file.original --rename $file
+                    fi
+		done
+            ;;
+    purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+
+    ;;
+
+    *)
+         echo "postrm called with unknown argument \`$1'" >&2
+         exit 1
+    ;;
+esac
+
 #DEBHELPER#
+
+exit 0
